spring:
  profiles:
    active:
    - dev
#    - native
  application:
    name: report-web
  cloud:
    inetutils:
      preferredNetworks: # 使用指定网卡
        - 10.0
        - 10.242
    config:
      discovery:
        enabled: true
#        service-id: configServer
      label: master
      profile: dev
      uri: http://localhost:8888
  cloud:
    consul:
      host: 192.168.56.201
      port: 8500
      discovery:
        enabled: true # To disable the Consul Discovery Client you can set spring.cloud.consul.discovery.enabled to false
        register: false # To disable the service registration you can set spring.cloud.consul.discovery.register to false.
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:@project.version@
        tags: k1=v1,urlprefix-/${spring.application.name}
    inetutils: # 忽略特定网卡
      ignoredInterfaces:
        - docker0
        - veth.*
      useOnlySiteLocalInterfaces: true  # 10.x, 172.x, 192.x 开头的内网地址
        
server:
  port: 8082
  
  
management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude:
        - test
        include:
        - info
        - health
        - features
        - env
  
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - info
#        - features
#        - health
  
#client:
#  ribbon:
#    MaxAutoRetries: 3 


k1=v1_app_dev
