server:
  port: 8082

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
          - 192.168.56.201:9092
          - 192.168.56.202:9092
          - 192.168.56.203:9092
    consul:
      host: 192.168.56.201
      port: 8500
      discovery:
        enabled: true # To disable the Consul Discovery Client you can set spring.cloud.consul.discovery.enabled to false
        register: true # To disable the service registration you can set spring.cloud.consul.discovery.register to false.
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:rwdev
        tags: k1=v1,group1,urlprefix-/${spring.application.name}
        
k1: v1_rw_dev_u6
k2: v2_rw_dev
kksec: '{cipher}FKSAJDFGYOS8F7GLHAKERGFHLSAJ'

management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
