server:
  port: 8082
  
spring:
  cloud:
    consul:
      host: 192.168.56.201
      port: 8500
      discovery:
        enabled: true # To disable the Consul Discovery Client you can set spring.cloud.consul.discovery.enabled to false
        register: true # To disable the service registration you can set spring.cloud.consul.discovery.register to false.
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}:rw
        tags: k1=v1,urlprefix-/${spring.application.name}
        
        
management:
  endpoint:
    beans:
      enabled: true
  endpoints:
    web:
      exposure:
        exclude:
        - test
        include: info, health, features, env, prometheus,metrics,httptrace,threaddump,heapdump,springmetrics,refresh
        
k1: v1
